### This is the Terraform-generated dev-build.yml workflow for the hrqb-client-dev app repository ###
### If this is a Lambda repo, uncomment the FUNCTION line at the end of the document     ###
### If the container requires any additional pre-build commands, uncomment and edit      ###
### the PREBUILD line at the end of the document.                                        ###
name: Dev Container Build and Deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: Dev Container Deploy
    uses: mitlibraries/.github/.github/workflows/ecr-shared-deploy-dev.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "hrqb-client-gha-dev"
      ECR: "hrqb-client-dev"
      # FUNCTION: ""
      # PREBUILD: 
